name: lint

on:
  push:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only physical_validation

      - name: Run black
        run: |
          black physical_validation --check

      - name: Run flake8
        run: |
          flake8 physical_validation
